const data = {
  "data": "success",
  "dataobj": {
      "visa_form": [
          {
              "name": "contact_information",
              "label": "Contact Information",
              "sub_label": "Current contact details for effective communication during the visa processing period.",
              "type": "group",
              "group_elements": [
                  {
                      "name": "applicants_telephone",
                      "label": "Phone Number",
                      "type": "textField",
                      "is_important": true,
                      "validations": {
                          "mandatory": true,
                          "min_length": 2,
                          "special_char": false,
                          "read_only": false,
                          "isDigit": true,
                          "display": true
                      },
                      "value": "",
                      "ocr_field": true,
                      "oneTimeUse": false
                  },
                  {
                      "name": "applicants_email",
                      "label": "Email",
                      "type": "textField",
                      "is_important": true,
                      "validations": {
                          "mandatory": true,
                          "min_length": 2,
                          "special_char": false,
                          "read_only": false,
                          "isDigit": false,
                          "display": true
                      },
                      "value": "",
                      "ocr_field": true,
                      "oneTimeUse": false
                  },
                  {
                      "name": "address_line1",
                      "label": "Home Address (If you don't find your street address, please enter your neighborhood, city and country)",
                      "type": "textField",
                      "is_important": true,
                      "validations": {
                          "mandatory": true,
                          "min_length": 2,
                          "special_char": false,
                          "read_only": false,
                          "isDigit": false,
                          "display": true
                      },
                      "value": "",
                      "ocr_field": true,
                      "oneTimeUse": false
                  },
                  {
                      "name": "occupation",
                      "label": "Occupation",
                      "type": "dropdown",
                      "is_important": false,
                      "validations": {
                          "mandatory": true,
                          "read_only": false,
                          "display": true
                      },
                      "options": [
                          "Accountant",
                          "Actuary",
                          "Administrator",
                          "Agricultural",
                          "Agriculturer",
                          "Air traffic pilots",
                          "Air traffic safety electronics technicians",
                          "Aircraft engine mechanics",
                          "Application Programmer",
                          "Architect",
                          "Artist",
                          "Assistant professor",
                          "Auditor",
                          "Authors",
                          "Bank Agent",
                          "Banker",
                          "Beautician",
                          "Biologist",
                          "Business Person",
                          "Cartographer",
                          "Cashier",
                          "Ceramics Technologist",
                          "Chef",
                          "Chemical Engineer",
                          "Chemical processing plant controller",
                          "Chemist",
                          "Chief Accountant",
                          "Chief Financial Officer",
                          "Civil Engineer",
                          "Civil Registration Officer",
                          "Civil servant",
                          "Clerk",
                          "Commercial Manager",
                          "Computer Scientist",
                          "Consultant",
                          "Contractor",
                          "Criminal Analyst",
                          "Criminal Record Officer",
                          "Customs Agencies",
                          "Dentist",
                          "Designer",
                          "Diplomat",
                          "Domestic Worker",
                          "Driver",
                          "Ecologist",
                          "Education Manager",
                          "Education Methods Specialist",
                          "Electrician",
                          "Electronics Engineer",
                          "Embassy Agent",
                          "Engineer",
                          "Environmental Engineer",
                          "Evangelist",
                          "Film",
                          "Food and beverage tasters and graders",
                          "Food Scientist",
                          "Football Coach",
                          "Geologist and Geophysicist",
                          "Glass Technologist",
                          "Health Adviser",
                          "Historian",
                          "Hospital (Medical) Administrator",
                          "Hotel Manager",
                          "Humanitarian Agent",
                          "Hydrometeorologist",
                          "Incinerator and water treatment",
                          "Industrial and Production Engineer",
                          "Information Technology Trainer",
                          "Interior designer",
                          "Jewelry precious metal worker",
                          "Journalist/Reporter",
                          "Judge",
                          "Landscape architects",
                          "Lawyer",
                          "Lecturer",
                          "Legal Advisor",
                          "Life science technician",
                          "Logistician",
                          "Manufacturing Manager",
                          "Mathematician",
                          "Mechanic",
                          "Mechanical Machinery Assembler",
                          "Medical and Pathology Laboratory Technician",
                          "Medical Doctor",
                          "Medical imaging and therapeutic equipment tech",
                          "Medical Practitioner",
                          "Member Of Parliament",
                          "Metal production process controllers",
                          "Midwifery Professional",
                          "Military",
                          "Mining",
                          "Missionary",
                          "Museum and library technicians",
                          "Notary",
                          "Nurse",
                          "Nutritionist",
                          "Optometrists and ophthalmic opticians",
                          "Pastor",
                          "Petroleum and natural gas refining plant op",
                          "Pharmacist",
                          "Physicist",
                          "Physiotherapist",
                          "Pilot",
                          "Plumber",
                          "Policeman/woman",
                          "Politician",
                          "Priest",
                          "Procurement Officer",
                          "Professor",
                          "Power production plant operator",
                          "Professional player",
                          "Product and garment designers",
                          "Professionally Qualified TVET Trainer",
                          "Psychologist",
                          "Public Prosecution Officer",
                          "Religious leader",
                          "Researcher",
                          "Retired",
                          "Secretary",
                          "Securities and finance dealers",
                          "Sheet Metal Worker",
                          "Ship's engineer",
                          "Sociologist",
                          "Sports coaches and instructors",
                          "Statistician",
                          "Student",
                          "System analysts (IT)",
                          "Tax Expert/Fiscalist",
                          "Technical Production Director",
                          "Technician",
                          "Toolmaker and Related Worker",
                          "Trader",
                          "Tradeswoman",
                          "Traffic Planner",
                          "Translator",
                          "Underwater divers",
                          "UN Official",
                          "Unemployed",
                          "Values and Loss Assessors",
                          "Veterinarian",
                          "Wood processing and finishing",
                          "Other"
                      ],
                      "value": "",
                      "ocr_field": false,
                      "oneTimeUse": false
                  },
                  {
                      "name": "emergency_fullname",
                      "label": "Emergency Full Name Contact",
                      "type": "textField",
                      "is_important": true,
                      "validations": {
                          "mandatory": false,
                          "min_length": 2,
                          "special_char": false,
                          "read_only": false,
                          "isDigit": true,
                          "display": true
                      },
                      "value": "",
                      "ocr_field": true,
                      "oneTimeUse": false
                  },
                  {
                      "name": "phone_number",
                      "label": "Phone Number",
                      "type": "textField",
                      "is_important": true,
                      "validations": {
                          "mandatory": false,
                          "min_length": 2,
                          "special_char": false,
                          "read_only": false,
                          "isDigit": true,
                          "display": true
                      },
                      "value": "",
                      "ocr_field": true,
                      "oneTimeUse": false
                  }
              ]
          },
          {
              "name": "trip_information",
              "label": "Trip Information",
              "sub_label": "Details of Trip Information, for a smooth visa approval process.",
              "type": "group",
              "group_elements": [
                  {
                      "name": "reason_of_travel",
                      "label": "Reason of travel",
                      "type": "dropdown",
                      "is_important": false,
                      "validations": {
                          "mandatory": true,
                          "read_only": false,
                          "display": true
                      },
                      "options": [
                          "TOURISM"
                      ],
                      "value": "TOURISM",
                      "ocr_field": true,
                      "oneTimeUse": true
                  },
                  {
                      "name": "date_of_arrival",
                      "label": "Arrival Date",
                      "type": "dateControl",
                      "is_important": true,
                      "validations": {
                          "mandatory": true,
                          "read_only": false,
                          "format": "dd-MM-yyyy",
                          "display": true,
                          "when": "after"
                      },
                      "value": "",
                      "ocr_field": true,
                      "oneTimeUse": true
                  },
                  {
                      "name": "select_arrival_airport",
                      "label": "Select arrival airport in Kenya",
                      "type": "dropdown",
                      "is_important": false,
                      "validations": {
                          "mandatory": true,
                          "read_only": false,
                          "display": true
                      },
                      "options": [
                          "Eldoret International Airport (Nakuru)",
                          "Isiolo Airport (Isiolo)",
                          "Kisumu Airport (Kisumu)",
                          "Lokichoggio Airport (Lokichoggio)",
                          "Malindi Airport (Mombasa)",
                          "Wilson Airport (Nairobi)",
                          "Wajir Airport (Wajir)"
                      ],
                      "value": "",
                      "ocr_field": false,
                      "oneTimeUse": true
                  },
                  {
                      "name": "arrival_airline",
                      "label": "Arrival Airline",
                      "type": "dropdown",
                      "is_important": false,
                      "validations": {
                          "mandatory": true,
                          "read_only": false,
                          "display": true
                      },
                      "options": [
                          "Kenya Airways",
                          "Emirates",
                          "African Express Airways",
                          "Air Arabia",
                          "Air France",
                          "Airkenya Express",
                          "Airlink",
                          "Astral Aviation",
                          "British Airways",
                          "Charter or Other Airline",
                          "China Southern Airlines",
                          "Condor",
                          "Discover Airlines",
                          "EgyptAir",
                          "Emirates",
                          "Ethiopian Airlines",
                          "FlexFlight",
                          "Freedom Airline Express",
                          "IndiGo",
                          "Jubba Airways",
                          "KLM",
                          "Kenya Airways",
                          "Land Border",
                          "Lot",
                          "Lufthansa",
                          "Martinair Holland",
                          "Neos",
                          "Precision Air",
                          "Private Jet",
                          "Qatar Airways",
                          "RwandAir",
                          "Safarilink Aviation",
                          "Saudia",
                          "Swiss International Air Lines",
                          "Taquan Air",
                          "Turkish Airlines",
                          "Uganda Airlines"
                      ],
                      "value": "",
                      "ocr_field": false,
                      "oneTimeUse": true
                  },
                  {
                      "name": "arrival_flight_number",
                      "label": "Arrival Flight Number",
                      "type": "textField",
                      "is_important": true,
                      "validations": {
                          "mandatory": true,
                          "min_length": 2,
                          "special_char": false,
                          "read_only": false,
                          "isDigit": false,
                          "display": true
                      },
                      "value": "",
                      "ocr_field": false,
                      "oneTimeUse": true
                  },
                  {
                      "name": "country_of_origin_for_your_trip",
                      "label": "Select the country of origin for your trip",
                      "type": "dropdown",
                      "is_important": true,
                      "validations": {
                          "mandatory": true,
                          "read_only": false,
                          "display": true
                      },
                      "options": [
                          "AFGHANISTAN",
                          "ALBANIA",
                          "ALGERIA",
                          "ANDORRA",
                          "ANGOLA",
                          "ANTIGUA & BARBUDA",
                          "ARGENTINA",
                          "ARMENIA",
                          "AUSTRALIA",
                          "AUSTRIA",
                          "AZERBAIJAN",
                          "BAHAMAS",
                          "BAHRAIN",
                          "BANGLADESH",
                          "BARBADOS",
                          "BELGIUM",
                          "BELIZE",
                          "BENIN",
                          "BERMUDA",
                          "BHUTAN",
                          "BOLIVIA",
                          "BOSNIA AND HERZEG",
                          "BOTSWANA",
                          "BRAZIL",
                          "BRITAIN",
                          "BRUNEI",
                          "BULGARIA",
                          "BURKINA FASO",
                          "BURMA UNION MYANMAR",
                          "BURUNDI",
                          "CABO VERDE",
                          "CAMBODIA",
                          "CAMEROON",
                          "CANADA",
                          "CENTRAL AFRICA REP",
                          "CHAD",
                          "CHILE",
                          "CHINA",
                          "COLOMBIA",
                          "COMONWEALTH DOMINICA",
                          "COMOROS",
                          "CONGO",
                          "COSTARICA",
                          "CROATIA",
                          "CUBA",
                          "CYPRUS",
                          "CZECH",
                          "DAGHYSTAN",
                          "DAHOOMI",
                          "DEMOCRATIC REPUBLIC OF THE CONGO",
                          "DENMARK",
                          "DJIBOUTI",
                          "DOMINICAN",
                          "ECUADOR",
                          "EGYPT",
                          "EL SALVADOR",
                          "EMIRATES",
                          "ENTIAGO",
                          "Equatorial Guinea",
                          "ERITREN",
                          "ESTONIA",
                          "ETHIOPIA",
                          "Faroese",
                          "FIJI",
                          "FINLAND",
                          "FRANCE",
                          "FRENCH GUIANA",
                          "GABON",
                          "GAMBIA",
                          "GEORGIA",
                          "GERMANY",
                          "GHANA",
                          "GHINIA BISSAU",
                          "GREECE",
                          "GREENLAND",
                          "GRENADA",
                          "GUATAMALA",
                          "GUYANA",
                          "HAITI",
                          "HOLLAND",
                          "HONDURAS",
                          "HONG KONG",
                          "HUNGARY",
                          "ICELAND",
                          "INDIA",
                          "INDONESIA",
                          "INT",
                          "IRAN",
                          "IRAQ",
                          "IRELAND",
                          "ISRAEL",
                          "ITALY",
                          "IVORY COAST",
                          "JAMAICA",
                          "JAPAN",
                          "JORDAN",
                          "KAIMAN ISLAN",
                          "KALDUNIA NEW",
                          "KAZAKHESTAN",
                          "KENYA",
                          "KINGSTONE",
                          "KIRIBATI",
                          "KOSOVA",
                          "KURDISH",
                          "KUWAIT",
                          "Kyrgyzstani",
                          "LAOS",
                          "LATVIA",
                          "LATVIA RES",
                          "LEBANON",
                          "LESOTHO",
                          "LIBERIA",
                          "LIBYA",
                          "LIECHTENSTEIN",
                          "LITHUANIA",
                          "LUXEMBOURG",
                          "MACAU",
                          "MADAGASCAR",
                          "MALAWI",
                          "MALAYSIA",
                          "MALDIVES",
                          "MALI",
                          "MALTA",
                          "MARSHALL ISLAND",
                          "MARTINIQUE",
                          "MARYANA ISLAND",
                          "MAURITANIA",
                          "MAURITIUS",
                          "MEXICO",
                          "MICRONESIA",
                          "MOLDAVIA",
                          "MONACO",
                          "MONGOLIA",
                          "MONTENEGRO",
                          "MOROCCO",
                          "MOZAMBIQUE",
                          "NAMIBIA",
                          "NAURU",
                          "NEPAL",
                          "NEW GHINIA",
                          "NEW ZEALAND",
                          "NICARAGUA",
                          "NIGER",
                          "NIGERIA",
                          "NORTH KOREA",
                          "NORWAY",
                          "PAKISTAN",
                          "PALAU",
                          "PALESTINE",
                          "PANAMA",
                          "PAPUA NEW GUINEA",
                          "PARAGUAY",
                          "PERU",
                          "PHILIPPINES",
                          "POLAND",
                          "PORTUGAL",
                          "PUERTO RICO",
                          "QATAR",
                          "REPUBLIC OF MACEDONIA",
                          "REPUBLIC OF BELARUS",
                          "REPUBLIC OF SOMALILAND",
                          "REPUPLIC OF GUINEA",
                          "ROMANIA",
                          "RWANDA",
                          "RUSSIA",
                          "SAINT LUCIA",
                          "SAINT VINSENT",
                          "SAN MARINO",
                          "SAO TOME",
                          "SAUDI ARABIA",
                          "SENEGAL",
                          "SICHEL",
                          "SIERRA LEONE",
                          "SINGAPORE",
                          "SLOVAKIA",
                          "SLOVENIA",
                          "SOLOMON ISLAND",
                          "SOMALIA",
                          "SOUTH AFRICA",
                          "SOUTH KOREA",
                          "SOUTH SUDAN",
                          "SPAIN",
                          "SRI LANKA",
                          "ST CHRISTOPHER",
                          "ST HELENA",
                          "ST KITTS-NAVIS",
                          "SUDAN",
                          "SULTANATE OF OMAN",
                          "SURBIA",
                          "SURINAME",
                          "SWAZILAND",
                          "SWEDEN",
                          "SWIZERLAND",
                          "SYRIA",
                          "TAHITI",
                          "TAIWAN",
                          "TAJIKISTAN",
                          "TANZANIA",
                          "TASMANIA",
                          "THAILAND",
                          "TIMOR LESTE",
                          "TOGO",
                          "TONGA",
                          "TRINIDAD",
                          "TUNISIA",
                          "TURKEY",
                          "TURKMENISTAN",
                          "TUVALU",
                          "UNITED STATES OF AMERICA",
                          "UGANDA",
                          "UKRAINE",
                          "United Nations",
                          "URGWAY",
                          "UZBAKISTAN",
                          "VANUATU",
                          "VATICAN",
                          "VENEZUELA",
                          "VIETNAM",
                          "W SAMOA",
                          "YEMEN",
                          "YUGOSLAVIA",
                          "ZAMBIA",
                          "ZIMBABWE"
                      ],
                      "value": "",
                      "ocr_field": true,
                      "oneTimeUse": true
                  },
                  {
                      "name": "date_of_departure",
                      "label": "Departure Date",
                      "type": "dateControl",
                      "is_important": true,
                      "validations": {
                          "mandatory": true,
                          "read_only": false,
                          "format": "dd-MM-yyyy",
                          "display": true,
                          "when": "after"
                      },
                      "value": "",
                      "ocr_field": true,
                      "oneTimeUse": true
                  },
                  {
                      "name": "select_depature_airport",
                      "label": "Departure Airport in Kenya",
                      "type": "dropdown",
                      "is_important": false,
                      "validations": {
                          "mandatory": true,
                          "read_only": false,
                          "display": true
                      },
                      "options": [
                          "Eldoret International Airport (Nakuru)",
                          "Isiolo Airport (Isiolo)",
                          "Kisumu Airport (Kisumu)",
                          "Lokichoggio Airport (Lokichoggio)",
                          "Malindi Airport (Mombasa)",
                          "Wilson Airport (Nairobi)",
                          "Wajir Airport (Wajir)"
                      ],
                      "value": "",
                      "ocr_field": false,
                      "oneTimeUse": true
                  },
                  {
                      "name": "departure_airline",
                      "label": "Departure Airline",
                      "type": "dropdown",
                      "is_important": false,
                      "validations": {
                          "mandatory": true,
                          "read_only": false,
                          "display": true
                      },
                      "options": [
                          "Kenya Airways",
                          "Emirates",
                          "African Express Airways",
                          "Air Arabia",
                          "Air France",
                          "Airkenya Express",
                          "Airlink",
                          "Astral Aviation",
                          "British Airways",
                          "Charter or Other Airline",
                          "China Southern Airlines",
                          "Condor",
                          "Discover Airlines",
                          "EgyptAir",
                          "Emirates",
                          "Ethiopian Airlines",
                          "FlexFlight",
                          "Freedom Airline Express",
                          "IndiGo",
                          "Jubba Airways",
                          "KLM",
                          "Kenya Airways",
                          "Land Border",
                          "Lot",
                          "Lufthansa",
                          "Martinair Holland",
                          "Neos",
                          "Precision Air",
                          "Private Jet",
                          "Qatar Airways",
                          "RwandAir",
                          "Safarilink Aviation",
                          "Saudia",
                          "Swiss International Air Lines",
                          "Taquan Air",
                          "Turkish Airlines",
                          "Uganda Airlines"
                      ],
                      "value": "",
                      "ocr_field": false,
                      "oneTimeUse": true
                  },
                  {
                      "name": "final_destination_country",
                      "label": "Destination Country",
                      "type": "dropdown",
                      "is_important": false,
                      "validations": {
                          "mandatory": false,
                          "read_only": false,
                          "display": true
                      },
                      "options": [
                          "Afghanistan",
                          "African Union",
                          "Albania",
                          "Algeria",
                          "American Samoa",
                          "Andorra",
                          "Angola",
                          "Anguilla",
                          "Antigua and Barbuda",
                          "Argentina",
                          "Armenia",
                          "Aruba",
                          "Ashmore and Cartier Islands",
                          "Australia",
                          "Austria",
                          "Azerbaijan",
                          "Bahamas",
                          "Bahrain",
                          "Bangladesh",
                          "Barbados",
                          "Belarus",
                          "Belgium",
                          "Belize",
                          "Benin",
                          "Bermuda",
                          "Bhutan",
                          "Bolivia",
                          "Bosnia and Herzegovina",
                          "Botswana",
                          "Brazil",
                          "Brunei",
                          "Bulgaria",
                          "Burkina Faso",
                          "Burma",
                          "Burundi",
                          "Cambodia",
                          "Cameroon",
                          "Canada",
                          "Cape Verde",
                          "Cayman Islands",
                          "Central African Republic",
                          "Chad",
                          "Chile",
                          "China",
                          "Cocos (Keeling) Islands",
                          "Colombia",
                          "COMESA",
                          "Comoros",
                          "Congo Brazzaville",
                          "Cook Islands",
                          "Costa Rica",
                          "Cote dIvoire",
                          "Croatia",
                          "Cuba",
                          "Cyprus",
                          "Czech Republic",
                          "Denmark",
                          "DEUTSCHLAND",
                          "Djibouti",
                          "Dominica",
                          "Dominican Republic",
                          "DR Congo",
                          "Ecuador",
                          "Egypt",
                          "El Salvador",
                          "Equatorial Guinea",
                          "Eritrea",
                          "Estonia",
                          "Ethiopia",
                          "Falkland Islands (Islas Malvinas)",
                          "Faroe Islands",
                          "Fiji",
                          "Finland",
                          "France",
                          "French Guiana",
                          "French Polynesia",
                          "French West Indies",
                          "Gabon",
                          "Gambia",
                          "Georgia",
                          "Ghana",
                          "Gibraltar",
                          "Greece",
                          "Greenland",
                          "Grenada",
                          "Guadeloupe",
                          "Guam",
                          "Guatemala",
                          "Guinea",
                          "Guinea Conakry",
                          "Guinea-Bissau",
                          "Guyana",
                          "Haiti",
                          "Holy See (Vatican City)",
                          "Honduras",
                          "Hungary",
                          "Iceland",
                          "India",
                          "Indonesia",
                          "Iran",
                          "Iraq",
                          "Ireland",
                          "Israel",
                          "Italy",
                          "Jamaica",
                          "Japan",
                          "Jordan",
                          "Kazakstan",
                          "Kenya",
                          "Kingdom of Eswatini",
                          "Kiribati",
                          "Korea",
                          "North - PRK",
                          "Korea",
                          "South",
                          "Kuwait",
                          "Kyrgyzstan",
                          "Laos",
                          "Latvia",
                          "Lebanon",
                          "Lesotho",
                          "Liberia",
                          "Libya",
                          "Liechtenstein",
                          "Lithuania",
                          "Luxembourg",
                          "Macau",
                          "Macedonia",
                          "Madagascar",
                          "Malawi",
                          "Malaysia",
                          "Maldives",
                          "Mali",
                          "Malta",
                          "Mauritania",
                          "Mauritius",
                          "Mexico",
                          "Moldova",
                          "Monaco",
                          "Mongolia",
                          "Montenegro",
                          "Morocco",
                          "Mozambique",
                          "Myanmar",
                          "Namibia",
                          "Nauru",
                          "Nepal",
                          "Netherlands",
                          "New Caledonia",
                          "New Zealand",
                          "Nicaragua",
                          "Niger",
                          "Nigeria",
                          "Norway",
                          "Oman",
                          "Pakistan",
                          "Palau",
                          "Palestine Territories",
                          "Panama",
                          "Papua New Guinea",
                          "Paraguay",
                          "Peru",
                          "Philippines",
                          "Poland",
                          "Portugal",
                          "Puerto Rico",
                          "Qatar",
                          "Romania",
                          "Russia",
                          "Rwanda",
                          "Saint Kitts and Nevis",
                          "Saint Lucia",
                          "Samoa",
                          "San Marino",
                          "Sao Tome and Prince",
                          "Saudi Arabia",
                          "Senegal",
                          "Serbia",
                          "Seychelles",
                          "Sierra Leone",
                          "Singapore",
                          "Slovakia",
                          "Slovenia",
                          "Somalia",
                          "South Africa",
                          "SOUTH SUDAN",
                          "Spain",
                          "Sri Lanka",
                          "Sudan",
                          "Suriname",
                          "Sweden",
                          "Switzerland",
                          "Syria",
                          "Taiwan",
                          "Tajikistan",
                          "Tanzania",
                          "Thailand",
                          "Timor-Leste",
                          "Togo",
                          "Tonga",
                          "Trinidad and Tobago",
                          "Tunisia",
                          "Turkey",
                          "Turkmenistan",
                          "Uganda",
                          "Ukraine",
                          "United Arab Emirates",
                          "United Kingdom",
                          "United States of America",
                          "Uruguay",
                          "Utopia",
                          "Uzbekistan",
                          "Vanuatu",
                          "Venezuela",
                          "Vietnam",
                          "Virgin Islands",
                          "Yemen",
                          "Zambia",
                          "Zimbabwe"
                      ],
                      "value": "",
                      "ocr_field": false,
                      "oneTimeUse": true
                  },
                  {
                      "name": "where_are_you_staying_in_kenya",
                      "label": "Where are you staying in Kenya?",
                      "type": "textField",
                      "is_important": true,
                      "validations": {
                          "mandatory": true,
                          "read_only": false,
                          "display": true
                      },
                      "value": "",
                      "ocr_field": false,
                      "oneTimeUse": true
                  },
                  {
                      "name": "date_from",
                      "label": "From Date",
                      "type": "dateControl",
                      "is_important": true,
                      "validations": {
                          "mandatory": true,
                          "read_only": false,
                          "format": "dd-MM-yyyy",
                          "display": true,
                          "when": "after"
                      },
                      "value": "",
                      "ocr_field": true,
                      "oneTimeUse": true
                  },
                  {
                      "name": "to_date",
                      "label": "To Date",
                      "type": "dateControl",
                      "is_important": true,
                      "validations": {
                          "mandatory": true,
                          "read_only": false,
                          "format": "dd-MM-yyyy",
                          "display": true,
                          "when": "after"
                      },
                      "value": "",
                      "ocr_field": true,
                      "oneTimeUse": true
                  }
              ]
          },
          {
              "name": "general_information",
              "label": "General Information",
              "sub_label": "General Information required for identification purposes in the visa application.",
              "type": "group",
              "group_elements": [
                  {
                      "name": "birth_country",
                      "label": "Country of Birth",
                      "type": "dropdown",
                      "is_important": true,
                      "validations": {
                          "mandatory": true,
                          "read_only": false,
                          "display": true
                      },
                      "options": [
                          "AFGHANISTAN",
                          "ALBANIA",
                          "ALGERIA",
                          "ANDORRA",
                          "ANGOLA",
                          "ANTIGUA & BARBUDA",
                          "ARGENTINA",
                          "ARMENIA",
                          "AUSTRALIA",
                          "AUSTRIA",
                          "AZERBAIJAN",
                          "BAHAMAS",
                          "BAHRAIN",
                          "BANGLADESH",
                          "BARBADOS",
                          "BELGIUM",
                          "BELIZE",
                          "BENIN",
                          "BERMUDA",
                          "BHUTAN",
                          "BOLIVIA",
                          "BOSNIA AND HERZEG",
                          "BOTSWANA",
                          "BRAZIL",
                          "BRITAIN",
                          "BRUNEI",
                          "BULGARIA",
                          "BURKINA FASO",
                          "BURMA UNION MYANMAR",
                          "BURUNDI",
                          "CABO VERDE",
                          "CAMBODIA",
                          "CAMEROON",
                          "CANADA",
                          "CENTRAL AFRICA REP",
                          "CHAD",
                          "CHILE",
                          "CHINA",
                          "COLOMBIA",
                          "COMONWEALTH DOMINICA",
                          "COMOROS",
                          "CONGO",
                          "COSTARICA",
                          "CROATIA",
                          "CUBA",
                          "CYPRUS",
                          "CZECH",
                          "DAGHYSTAN",
                          "DAHOOMI",
                          "DEMOCRATIC REPUBLIC OF THE CONGO",
                          "DENMARK",
                          "DJIBOUTI",
                          "DOMINICAN",
                          "ECUADOR",
                          "EGYPT",
                          "EL SALVADOR",
                          "EMIRATES",
                          "ENTIAGO",
                          "Equatorial Guinea",
                          "ERITREN",
                          "ESTONIA",
                          "ETHIOPIA",
                          "Faroese",
                          "FIJI",
                          "FINLAND",
                          "FRANCE",
                          "FRENCH GUIANA",
                          "GABON",
                          "GAMBIA",
                          "GEORGIA",
                          "GERMANY",
                          "GHANA",
                          "GHINIA BISSAU",
                          "GREECE",
                          "GREENLAND",
                          "GRENADA",
                          "GUATAMALA",
                          "GUYANA",
                          "HAITI",
                          "HOLLAND",
                          "HONDURAS",
                          "HONG KONG",
                          "HUNGARY",
                          "ICELAND",
                          "INDIA",
                          "INDONESIA",
                          "INT",
                          "IRAN",
                          "IRAQ",
                          "IRELAND",
                          "ISRAEL",
                          "ITALY",
                          "IVORY COAST",
                          "JAMAICA",
                          "JAPAN",
                          "JORDAN",
                          "KAIMAN ISLAN",
                          "KALDUNIA NEW",
                          "KAZAKHESTAN",
                          "KENYA",
                          "KINGSTONE",
                          "KIRIBATI",
                          "KOSOVA",
                          "KURDISH",
                          "KUWAIT",
                          "Kyrgyzstani",
                          "LAOS",
                          "LATVIA",
                          "LATVIA RES",
                          "LEBANON",
                          "LESOTHO",
                          "LIBERIA",
                          "LIBYA",
                          "LIECHTENSTEIN",
                          "LITHUANIA",
                          "LUXEMBOURG",
                          "MACAU",
                          "MADAGASCAR",
                          "MALAWI",
                          "MALAYSIA",
                          "MALDIVES",
                          "MALI",
                          "MALTA",
                          "MARSHALL ISLAND",
                          "MARTINIQUE",
                          "MARYANA ISLAND",
                          "MAURITANIA",
                          "MAURITIUS",
                          "MEXICO",
                          "MICRONESIA",
                          "MOLDAVIA",
                          "MONACO",
                          "MONGOLIA",
                          "MONTENEGRO",
                          "MOROCCO",
                          "MOZAMBIQUE",
                          "NAMIBIA",
                          "NAURU",
                          "NEPAL",
                          "NEW GHINIA",
                          "NEW ZEALAND",
                          "NICARAGUA",
                          "NIGER",
                          "NIGERIA",
                          "NORTH KOREA",
                          "NORWAY",
                          "PAKISTAN",
                          "PALAU",
                          "PALESTINE",
                          "PANAMA",
                          "PAPUA NEW GUINEA",
                          "PARAGUAY",
                          "PERU",
                          "PHILIPPINES",
                          "POLAND",
                          "PORTUGAL",
                          "PUERTO RICO",
                          "QATAR",
                          "REPUBLIC OF MACEDONIA",
                          "REPUBLIC OF BELARUS",
                          "REPUBLIC OF SOMALILAND",
                          "REPUPLIC OF GUINEA",
                          "ROMANIA",
                          "RWANDA",
                          "RUSSIA",
                          "SAINT LUCIA",
                          "SAINT VINSENT",
                          "SAN MARINO",
                          "SAO TOME",
                          "SAUDI ARABIA",
                          "SENEGAL",
                          "SICHEL",
                          "SIERRA LEONE",
                          "SINGAPORE",
                          "SLOVAKIA",
                          "SLOVENIA",
                          "SOLOMON ISLAND",
                          "SOMALIA",
                          "SOUTH AFRICA",
                          "SOUTH KOREA",
                          "SOUTH SUDAN",
                          "SPAIN",
                          "SRI LANKA",
                          "ST CHRISTOPHER",
                          "ST HELENA",
                          "ST KITTS-NAVIS",
                          "SUDAN",
                          "SULTANATE OF OMAN",
                          "SURBIA",
                          "SURINAME",
                          "SWAZILAND",
                          "SWEDEN",
                          "SWIZERLAND",
                          "SYRIA",
                          "TAHITI",
                          "TAIWAN",
                          "TAJIKISTAN",
                          "TANZANIA",
                          "TASMANIA",
                          "THAILAND",
                          "TIMOR LESTE",
                          "TOGO",
                          "TONGA",
                          "TRINIDAD",
                          "TUNISIA",
                          "TURKEY",
                          "TURKMENISTAN",
                          "TUVALU",
                          "UNITED STATES OF AMERICA",
                          "UGANDA",
                          "UKRAINE",
                          "United Nations",
                          "URGWAY",
                          "UZBAKISTAN",
                          "VANUATU",
                          "VATICAN",
                          "VENEZUELA",
                          "VIETNAM",
                          "W SAMOA",
                          "YEMEN",
                          "YUGOSLAVIA",
                          "ZAMBIA",
                          "ZIMBABWE"
                      ],
                      "value": "",
                      "ocr_field": true,
                      "oneTimeUse": false
                  },
                  {
                      "name": "nationality_at_birth",
                      "label": "Nationality At Birth",
                      "type": "dropdown",
                      "is_important": true,
                      "validations": {
                          "mandatory": true,
                          "read_only": false,
                          "display": true
                      },
                      "options": [
                          "AFGHANISTAN",
                          "ALBANIA",
                          "ALGERIA",
                          "ANDORRA",
                          "ANGOLA",
                          "ANTIGUA & BARBUDA",
                          "ARGENTINA",
                          "ARMENIA",
                          "AUSTRALIA",
                          "AUSTRIA",
                          "AZERBAIJAN",
                          "BAHAMAS",
                          "BAHRAIN",
                          "BANGLADESH",
                          "BARBADOS",
                          "BELGIUM",
                          "BELIZE",
                          "BENIN",
                          "BERMUDA",
                          "BHUTAN",
                          "BOLIVIA",
                          "BOSNIA AND HERZEG",
                          "BOTSWANA",
                          "BRAZIL",
                          "BRITAIN",
                          "BRUNEI",
                          "BULGARIA",
                          "BURKINA FASO",
                          "BURMA UNION MYANMAR",
                          "BURUNDI",
                          "CABO VERDE",
                          "CAMBODIA",
                          "CAMEROON",
                          "CANADA",
                          "CENTRAL AFRICA REP",
                          "CHAD",
                          "CHILE",
                          "CHINA",
                          "COLOMBIA",
                          "COMONWEALTH DOMINICA",
                          "COMOROS",
                          "CONGO",
                          "COSTARICA",
                          "CROATIA",
                          "CUBA",
                          "CYPRUS",
                          "CZECH",
                          "DAGHYSTAN",
                          "DAHOOMI",
                          "DEMOCRATIC REPUBLIC OF THE CONGO",
                          "DENMARK",
                          "DJIBOUTI",
                          "DOMINICAN",
                          "ECUADOR",
                          "EGYPT",
                          "EL SALVADOR",
                          "EMIRATES",
                          "ENTIAGO",
                          "Equatorial Guinea",
                          "ERITREN",
                          "ESTONIA",
                          "ETHIOPIA",
                          "Faroese",
                          "FIJI",
                          "FINLAND",
                          "FRANCE",
                          "FRENCH GUIANA",
                          "GABON",
                          "GAMBIA",
                          "GEORGIA",
                          "GERMANY",
                          "GHANA",
                          "GHINIA BISSAU",
                          "GREECE",
                          "GREENLAND",
                          "GRENADA",
                          "GUATAMALA",
                          "GUYANA",
                          "HAITI",
                          "HOLLAND",
                          "HONDURAS",
                          "HONG KONG",
                          "HUNGARY",
                          "ICELAND",
                          "INDIA",
                          "INDONESIA",
                          "INT",
                          "IRAN",
                          "IRAQ",
                          "IRELAND",
                          "ISRAEL",
                          "ITALY",
                          "IVORY COAST",
                          "JAMAICA",
                          "JAPAN",
                          "JORDAN",
                          "KAIMAN ISLAN",
                          "KALDUNIA NEW",
                          "KAZAKHESTAN",
                          "KENYA",
                          "KINGSTONE",
                          "KIRIBATI",
                          "KOSOVA",
                          "KURDISH",
                          "KUWAIT",
                          "Kyrgyzstani",
                          "LAOS",
                          "LATVIA",
                          "LATVIA RES",
                          "LEBANON",
                          "LESOTHO",
                          "LIBERIA",
                          "LIBYA",
                          "LIECHTENSTEIN",
                          "LITHUANIA",
                          "LUXEMBOURG",
                          "MACAU",
                          "MADAGASCAR",
                          "MALAWI",
                          "MALAYSIA",
                          "MALDIVES",
                          "MALI",
                          "MALTA",
                          "MARSHALL ISLAND",
                          "MARTINIQUE",
                          "MARYANA ISLAND",
                          "MAURITANIA",
                          "MAURITIUS",
                          "MEXICO",
                          "MICRONESIA",
                          "MOLDAVIA",
                          "MONACO",
                          "MONGOLIA",
                          "MONTENEGRO",
                          "MOROCCO",
                          "MOZAMBIQUE",
                          "NAMIBIA",
                          "NAURU",
                          "NEPAL",
                          "NEW GHINIA",
                          "NEW ZEALAND",
                          "NICARAGUA",
                          "NIGER",
                          "NIGERIA",
                          "NORTH KOREA",
                          "NORWAY",
                          "PAKISTAN",
                          "PALAU",
                          "PALESTINE",
                          "PANAMA",
                          "PAPUA NEW GUINEA",
                          "PARAGUAY",
                          "PERU",
                          "PHILIPPINES",
                          "POLAND",
                          "PORTUGAL",
                          "PUERTO RICO",
                          "QATAR",
                          "REPUBLIC OF MACEDONIA",
                          "REPUBLIC OF BELARUS",
                          "REPUBLIC OF SOMALILAND",
                          "REPUPLIC OF GUINEA",
                          "ROMANIA",
                          "RWANDA",
                          "RUSSIA",
                          "SAINT LUCIA",
                          "SAINT VINSENT",
                          "SAN MARINO",
                          "SAO TOME",
                          "SAUDI ARABIA",
                          "SENEGAL",
                          "SICHEL",
                          "SIERRA LEONE",
                          "SINGAPORE",
                          "SLOVAKIA",
                          "SLOVENIA",
                          "SOLOMON ISLAND",
                          "SOMALIA",
                          "SOUTH AFRICA",
                          "SOUTH KOREA",
                          "SOUTH SUDAN",
                          "SPAIN",
                          "SRI LANKA",
                          "ST CHRISTOPHER",
                          "ST HELENA",
                          "ST KITTS-NAVIS",
                          "SUDAN",
                          "SULTANATE OF OMAN",
                          "SURBIA",
                          "SURINAME",
                          "SWAZILAND",
                          "SWEDEN",
                          "SWIZERLAND",
                          "SYRIA",
                          "TAHITI",
                          "TAIWAN",
                          "TAJIKISTAN",
                          "TANZANIA",
                          "TASMANIA",
                          "THAILAND",
                          "TIMOR LESTE",
                          "TOGO",
                          "TONGA",
                          "TRINIDAD",
                          "TUNISIA",
                          "TURKEY",
                          "TURKMENISTAN",
                          "TUVALU",
                          "UNITED STATES OF AMERICA",
                          "UGANDA",
                          "UKRAINE",
                          "United Nations",
                          "URGWAY",
                          "UZBAKISTAN",
                          "VANUATU",
                          "VATICAN",
                          "VENEZUELA",
                          "VIETNAM",
                          "W SAMOA",
                          "YEMEN",
                          "YUGOSLAVIA",
                          "ZAMBIA",
                          "ZIMBABWE"
                      ],
                      "value": "",
                      "ocr_field": true,
                      "oneTimeUse": false
                  },
                  {
                      "name": "marital_status",
                      "label": "Marital Status",
                      "type": "dropdown",
                      "is_important": false,
                      "validations": {
                          "mandatory": true,
                          "read_only": false,
                          "display": true
                      },
                      "options": [
                          "SINGLE",
                          "MARRIED",
                          "DIVORCED",
                          "WIDOW",
                          "UNSPECIFIC"
                      ],
                      "value": "",
                      "ocr_field": true,
                      "oneTimeUse": false
                  },
                  {
                      "name": "have_you_ever_previously_traveled_to_kenya",
                      "label": "Have you previously traveled to Kenya?",
                      "type": "dropdown",
                      "is_important": false,
                      "validations": {
                          "mandatory": true,
                          "read_only": false,
                          "display": true
                      },
                      "options": [
                          "YES",
                          "NO"
                      ],
                      "value": "",
                      "ocr_field": false,
                      "oneTimeUse": false
                  },
                  {
                      "name": "have_you_ever_previously_denied_entry_to_kenya",
                      "label": "Have you ever been previously denied entry to Kenya?",
                      "type": "dropdown",
                      "is_important": false,
                      "validations": {
                          "mandatory": true,
                          "read_only": false,
                          "display": true
                      },
                      "options": [
                          "YES",
                          "NO"
                      ],
                      "value": "",
                      "ocr_field": false,
                      "oneTimeUse": false
                  },
                  {
                      "name": "have_you_ever_been_convicted_of_any_offence_in_last_5_years",
                      "label": "Have you ever been convicted of any offence, under any system of law, in the past 5 years?",
                      "type": "dropdown",
                      "is_important": false,
                      "validations": {
                          "mandatory": true,
                          "read_only": false,
                          "display": true
                      },
                      "options": [
                          "YES",
                          "NO"
                      ],
                      "value": "",
                      "ocr_field": false,
                      "oneTimeUse": false
                  },
                  {
                      "name": "is_your_trip_financed_by_a_third_party_which_is_not_employer_nor_government",
                      "label": "Is your trip financed by a third party, which is not your employer nor a government?",
                      "type": "dropdown",
                      "is_important": false,
                      "validations": {
                          "mandatory": true,
                          "read_only": false,
                          "display": true
                      },
                      "options": [
                          "YES",
                          "NO"
                      ],
                      "value": "",
                      "ocr_field": false,
                      "oneTimeUse": false
                  }
              ]
          },
          {
              "name": "customs_declaration",
              "label": "Customs Declaration",
              "sub_label": "Customs Declaration required for identification purposes in the visa application.",
              "type": "group",
              "group_elements": [
                  {
                      "name": "are_you_bringing_into_republic_of_kenya_currency_or_monetary_instruments_over",
                      "label": "Will you be bringing into Republic of Kenya currency or monetary instruments of a value greater than $5000 or foreign equivalent?",
                      "type": "dropdown",
                      "is_important": false,
                      "validations": {
                          "mandatory": true,
                          "read_only": false,
                          "display": true
                      },
                      "options": [
                          "YES",
                          "NO"
                      ],
                      "value": "",
                      "ocr_field": false,
                      "oneTimeUse": false,
                      "dependent_elements": [
                          {
                              "name": "are_you_bringing_into_republic_of_kenya_currency_or_monetary_instruments_over_information",
                              "label": "Are you bringing into Republic of Kenya currency or monetary instruments over $5,000.00 US (or foreign equivalent) Information?",
                              "type": "subGroup",
                              "dependent_value": "YES",
                              "sub_group_elements": [
                                  [
                                      {
                                          "name": "select_currency",
                                          "label": "Select Currency",
                                          "dependant_on": "are_you_bringing_into_republic_of_kenya_currency_or_monetary_instruments_over",
                                          "dependant_value": "YES",
                                          "type": "dropdown",
                                          "is_important": false,
                                          "validations": {
                                              "mandatory": true,
                                              "read_only": false,
                                              "display": true
                                          },
                                          "options": [
                                              "USD",
                                              "KES",
                                              "EUR",
                                              "CNY",
                                              "INR"
                                          ],
                                          "value": "",
                                          "ocr_field": false,
                                          "oneTimeUse": false
                                      },
                                      {
                                          "name": "amount",
                                          "label": "Amount",
                                          "dependant_on": "are_you_bringing_into_republic_of_kenya_currency_or_monetary_instruments_over",
                                          "dependant_value": "YES",
                                          "type": "textField",
                                          "is_important": false,
                                          "validations": {
                                              "mandatory": true,
                                              "read_only": false,
                                              "display": true
                                          },
                                          "value": "",
                                          "ocr_field": false,
                                          "oneTimeUse": false
                                      }
                                  ]
                              ]
                          }
                      ]
                  }
              ]
          }
      ],
      "visa_document": [
          {
              "doc_type": "passport_front",
              "doc_name": "passport_first_page",
              "status": "uploaded",
              "doc_url": "https://s3.amazonaws.com/visaero.prod.application.data/document_1716396659623_Passport_of_Serbia_ID%2C_2009_version.jpg?AWSAccessKeyId=AKIARJMDR2S6XTXA2WVF&Expires=1716400287&Signature=wG1FVMaV1qhLS3jCGd10t%2BGGSbQ%3D",
              "doc_thumbnail": "https://s3.amazonaws.com/visaero.prod.application.data/thumb_document_1716396659623_Passport_of_Serbia_ID%2C_2009_version.jpg?AWSAccessKeyId=AKIARJMDR2S6XTXA2WVF&Expires=1716400287&Signature=Be1lJ7tpIj%2Fr95pw9JydBtNo2Xo%3D",
              "ocr_processed": true
          },
          {
              "doc_type": "passport_back",
              "doc_name": "passport_last_page",
              "status": "pending",
              "doc_url": "",
              "doc_thumbnail": "",
              "ocr_processed": false
          },
          {
              "doc_type": "photo",
              "doc_name": "applicant_photo",
              "status": "pending",
              "doc_url": "",
              "doc_thumbnail": "",
              "ocr_processed": false
          },
          {
              "doc_type": "hotel_accomodation",
              "doc_name": "hotel_accomodation",
              "status": "pending",
              "doc_url": "",
              "doc_thumbnail": "",
              "ocr_processed": false
          }
      ],
      "data_dictionary": {}
  },
  "applicant_obj": {
      "_id": "664e228b534bc710ee7c2081",
      "application_id": "664e228b534bc710ee7c207f",
      "user_id": "664e2243534bc710ee7c207e",
      "applicant_master_id": "DYi4IE77SYpaHG9v",
      "visaero_group_id": "foorffqty6tvcukf",
      "applicant_first_name": "MILICA",
      "applicant_last_name": "TEST",
      "default_fname": "MILICA",
      "default_lname": "TEST",
      "travelling_to": "KEN",
      "travelling_to_identity": "IND_IND_KEN",
      "traveller_type": "adult",
      "isPrimaryApplicant": true,
      "gender": "ZIF",
      "age": 56,
      "visa_id": "master.IND_IND_KEN.KEN_tourist_standard_30_days_single",
      "documents_ocr_done": true,
      "journey_start_date": "2024-05-24T16:50:11.580Z",
      "journey_end_date": "2024-05-28T16:50:11.580Z",
      "sequence_number": 0,
      "applicant_display_status": "",
      "visa_status": "pending",
      "host": "visaero",
      "created_on": 1716396683922,
      "updated_on": 1716396683922,
      "structure": "new",
      "visa_form_brule": {
          "name": "visa_form_template",
          "travelling_to_identity": "",
          "destination": "KEN",
          "host": "visaero",
          "structure": "new"
      }
  }
}